@extends('layouts/layout-portfolio')

@section('content')
<div class="row gy-4">

    <div class="col-lg-4">
        <div class="portfolio-details-slider swiper-container">
            <div class="swiper-slide">
            <img src="assets/img/References/MAROC-PME.jpg" class="img-fluid" alt="" />
            </div>
            <div class="swiper-pagination"></div>
        </div>
    </div>

    <div class="col-lg-8">
        <div class="portfolio-description">
            <h2>PRESTATIONS DE SERVICES</h2>
            <p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Il s&rsquo;agit d&rsquo;une nouvelle offre au profit des PME ayant un chiffre d&rsquo;affaires entre 10 et 200 millions de dirhams (10 &le;CA&le; 200 MDHS) en phase de croissance ou de changement d&rsquo;&eacute;chelle souhaitant le renforcement de leur comp&eacute;titivit&eacute;.</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 18pt; padding: 0px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">A travers cette offre Maroc PME&reg;, tend &agrave; r&eacute;pondre aux besoins des entreprises en mati&egrave;re d&rsquo;assistance technique, de transfert de comp&eacute;tences et de d&eacute;veloppement num&eacute;rique.</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 6pt; padding: 0px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Les leviers de performance vis&eacute;s sont :</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Strat&eacute;gie de d&eacute;veloppement &amp; Restructuration des entreprises ;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Accompagnement du dirigeant &amp; Gouvernance ;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Performances op&eacute;rationnelles ;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">D&eacute;veloppement num&eacute;rique ;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">D&eacute;veloppement des march&eacute;s ;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Management de l&rsquo;innovation ;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px 0px 0px 30px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; font-family: Wingdings; color: red;">&sect;</span><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">Acc&egrave;s au capital.</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">&nbsp;</span></p>
            <p class="MsoNormal" style="margin: 0px 0px 0.0001pt; padding: 0px; outline: 0px; font-family: Raleway, sans-serif; font-size: 15px; text-align: justify; line-height: 15pt; vertical-align: baseline;"><strong style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt; color: red;">ABS COMPETENCES</span></strong>&nbsp;<span style="margin: 0px; padding: 0px; outline: 0px; font-size: 12pt;">vous accompagnera dans toutes les d&eacute;marches de Pr&eacute;paration des documents administratifs.</span></p>
            </p>

        </div>
    </div>

</div>

@endsection